sync:
	rsync -av --include="*/" --include="昭和橋*.csv" --exclude="*" ../../../../yamanashi-water/flow/ ./data/
	rsync -av --include="*/" --include="大月橋*.csv" --exclude="*" ../../../../yamanashi-water/flow/ ./data/
	rsync -av --include="*/" --include="桂川橋*.csv" --exclude="*" ../../../../yamanashi-water/flow/ ./data/
